=== denone2000/JD2018-08-21/src/by/it/artemliashkov/jd02_07/Companies.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Companies (Company)+>
        <!ELEMENT Company (Name, Role, Country, AmountAgents,Agents)>
        <!ELEMENT Name  (#PCDATA)>
        <!ELEMENT Role (#PCDATA)>
        <!ELEMENT Country (#PCDATA)>
        <!ELEMENT AmountAgents (#PCDATA)>
        <!ELEMENT Agents (Agent)+>
        <!ELEMENT Agent (Name, Address)>
        <!ELEMENT NameAgent (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>

=== denone2000/JD2018-08-21/src/by/it/artemliashkov/jd02_07/Companies+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Companies SYSTEM "Companies.dtd">
<Companies>
    <Company>
        <Name>Компания ТАСК</Name>
        <Role>Страховая</Role>
        <Country>Беларусь</Country>
        <AmountAgents>3278</AmountAgents>
        <Agents>
            <Agent>
                <Name>Вера Николаевна</Name>
                <Address>ул. Острошицкая 11</Address>
            </Agent>
            <Agent>
                <Name>Анна Сергеевна</Name>
                <Address>пр. Независимости 73</Address>
            </Agent>
        </Agents>
    </Company>
    <Company>
        <Name>Компания Белнефтестрах</Name>
        <Role>Страховая</Role>
        <Country>Беларусь</Country>
        <AmountAgents>612</AmountAgents>
        <Agents>
            <Agent>
                <Name>Галина Александрова</Name>
                <Address>ул. Городецкая 36</Address>
            </Agent>
            <Agent>
                <Name>Инна Тарасовна</Name>
                <Address>ул. Академика Купревича 27</Address>
            </Agent>
        </Agents>
    </Company>
</Companies>
