=== denone2000/JD2018-08-21/src/by/it/korolchuk/jd02_07/jd02_07_HT/Theatres.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://korolchuk.it.by/"
        xmlns:tns="http://korolchuk.it.by/"
        elementFormDefault="qualified">
    <element name="Theatres">
        <complexType>
            <sequence>
                <element name="Theatre"
                         type="tns:Theatre"
                         minOccurs="0"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Theatre">
        <sequence>
            <element name="TheatreName" type="string"/>
            <element name="Address" type="string"/>
            <element name="Shows" type="tns:Shows"/>
        </sequence>
    </complexType>
    <complexType name="Shows">
        <sequence>
            <element name="Show"
                     type="tns:Show"
                     minOccurs="0x"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Show">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Genre" type="string"/>
            <element name="Director" type="string"/>
        </sequence>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/korolchuk/jd02_07/jd02_07_HT/Theatres+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Theatres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns = "http://korolchuk.it.by/"
       xsi:schemaLocation="http://korolchuk.it.by/ Theatres.xsd"
>
        <Theatre>
            <TheatreName>РТБД</TheatreName>
            <Address>Кропоткина, 44</Address>
            <Shows>
                <Show>
                    <Name>Паляванне на сябе</Name>
                    <Genre>Не комедия</Genre>
                    <Director>Стас Жирков</Director>
                </Show>
                <Show>
                    <Name>Цiхi шэпат сыходзячых крокау</Name>
                    <Genre>Сон в двух действиях</Genre>
                    <Director>Шамиль Дыйканбаев</Director>
                </Show>
                <Show>
                    <Name>Сiндром Медэi</Name>
                    <Genre>Трагедия</Genre>
                    <Director>Екатерина Аверкова</Director>
                </Show>
            </Shows>
        </Theatre>
        <Theatre>
            <TheatreName>АртКорпорейшн</TheatreName>
            <Address>Октябрьская, 16</Address>
            <Shows>
                <Show>
                    <Name>Опиум</Name>
                    <Genre>-</Genre>
                    <Director>Александр Марченко</Director>
                </Show>
                <Show>
                    <Name>Крестовый поход детей</Name>
                    <Genre>экспериментальный театр</Genre>
                    <Director>Юра Диваков</Director>
                </Show>
                <Show>
                    <Name>С училища</Name>
                    <Genre>-</Genre>
                    <Director>Александр Марченко</Director>
                </Show>
            </Shows>
        </Theatre>
    </Theatres>
