=== denone2000/JD2018-08-21/src/by/it/basumatarau/jd02_09/Venues.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.basumatarau.it.by/"
        xmlns:tns="http://beans.jd02_09.basumatarau.it.by/"
        elementFormDefault="qualified">
    <element name="Venues">
        <complexType>
            <sequence>
                <element name="Venue"
                         type="tns:Venue"
                         maxOccurs="unbounded"
                />
            </sequence>
        </complexType>
    </element>
    <complexType name="Venue">
        <sequence>
            <element name="Name" type="string"/>
            <element name="TypeTags" type="tns:TypeTags"/>
            <element name="Description" type="string"/>
            <element name="Place" type="tns:Place"/>
            <element name="OpeningHours" type="string"/>
            <element name="OpeningDates" type="string"/>
            <element name="ParticipationFee" type="string"/>
        </sequence>
    </complexType>
    <complexType name="TypeTags">
        <sequence>
            <element name="TypeTag"
                     type="string"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>
    <complexType name="Place">
        <sequence>
            <element name="PlaceName" type="string"/>
            <element name="Address" type="string"/>
            <element name="IsOpenNow" type="string"/>
        </sequence>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/basumatarau/jd02_09/Venues_XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Venues xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://beans.jd02_09.basumatarau.it.by/"
        xsi:schemaLocation="http://beans.jd02_09.basumatarau.it.by/ Venues.xsd"
>
    <Venue>
        <Name>"Mozgoboynya"</Name>
        <TypeTags>
            <TypeTag>"quiz"</TypeTag>
            <TypeTag>"game"</TypeTag>
            <TypeTag>"show"</TypeTag>
        </TypeTags>
        <Description>"some venue description"</Description>
        <Place>
            <PlaceName>"Мулен Руж"</PlaceName>
            <Address>"Ulitsa Kal'variyskaya 1, Minsk 220004"</Address>
            <IsOpenNow>"no"</IsOpenNow>
        </Place>
        <OpeningHours>"20:30 - 22:00"</OpeningHours>
        <OpeningDates>"17 Oct"</OpeningDates>
        <ParticipationFee>"6.0 BYN"</ParticipationFee>
    </Venue>

    <Venue>
        <Name>"Wine Tasting"</Name>
        <TypeTags>
            <TypeTag>"wine"</TypeTag>
            <TypeTag>"fine-dining"</TypeTag>
        </TypeTags>
        <Description>"some venue description"</Description>
        <Place>
            <PlaceName>"Bistro de Luxe"</PlaceName>
            <Address>"Ulitsa Gorodskoy Val 10, Minsk 220030"</Address>
            <IsOpenNow>"yes"</IsOpenNow>
        </Place>
        <OpeningHours>"18:30 - 23:00"</OpeningHours>
        <OpeningDates>"18 Oct"</OpeningDates>
        <ParticipationFee>"10.0 BYN"</ParticipationFee>
    </Venue>
</Venues>
