=== denone2000/JD2018-08-21/src/by/it/voinilo/jd02/jd02_07/Persons.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Persons  (Person)+>
            <!ELEMENT Person (Email, Nickname, Password, Ads)>
            <!ELEMENT Email (#PCDATA)>
            <!ELEMENT Nickname (#PCDATA)>
            <!ELEMENT Password (#PCDATA)>
            <!ELEMENT Ads (Ad)+>
                <!ELEMENT Ad (Rooms, Description, Adress, Floor, Floors, Square, Price)+>
        <!ELEMENT Rooms (#PCDATA) >
        <!ELEMENT Description (#PCDATA) >
                    <!ELEMENT Adress (#PCDATA) >
                    <!ELEMENT Floor (#PCDATA) >
                    <!ELEMENT Floors (#PCDATA) >
                    <!ELEMENT Square (#PCDATA) >
                    <!ELEMENT Price (#PCDATA) >

=== denone2000/JD2018-08-21/src/by/it/voinilo/jd02/jd02_07/Persons+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Persons SYSTEM "Persons.dtd" >
<Persons>

    <Person>
        <Email>asd@mail.ru</Email>
        <Nickname>asd</Nickname>
        <Password>1234</Password>
        <Ads>
            <Ad >
                <Rooms>2</Rooms>
                <Description>Квартира в центре города</Description>
                <Adress>Пр.Пушкина 2-3-4</Adress>
                <Floor>2</Floor>
                <Floors>5</Floors>
                <Square>21</Square>
                <Price>300k</Price>
            </Ad>
            <Ad ><Rooms>3</Rooms>
                <Description>Квартира в спальном районе</Description>
                <Adress>Центральная, 212</Adress>
                <Floor>4</Floor>
                <Floors>10</Floors>
                <Square>43</Square>
                <Price>250k</Price>
            </Ad>
            <Ad ><Rooms>1</Rooms>
                <Description>Квартира рядом с метро</Description>
                <Adress>Победителей,24</Adress>
                <Floor>1</Floor>
                <Floors>10</Floors>
                <Square>25</Square>
                <Price>221k</Price>
            </Ad>
        </Ads>
    </Person>

</Persons>
