=== denone2000/JD2018-08-21/src/by/it/voinilo/jd02/jd02_09/Persons.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.jd02.voinilo.it.by/xml/Persons"
        xmlns:tns="http://beans.jd02_09.jd02.voinilo.it.by/xml/Persons"
        elementFormDefault="qualified">

    <element name="Persons">
       <complexType>
           <sequence>
               <element name="Person"
                        type ="tns:Person"
                        maxOccurs="unbounded">

               </element>
           </sequence>
       </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"></element>
            <element name="Nickname" type="string"></element>
            <element name="Password" type="string"></element>
            <element name="Ads" type="tns:Ads"></element>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
        <element name="Ad" type="tns:Ad" maxOccurs="unbounded"
                 minOccurs="1" ></element>
        </sequence>
    </complexType>

    <complexType name="Ad">

        <all>
            <element name="Rooms" type="string"></element>
            <element name="Description" type="string"></element>
            <element name="Addres" type="string"></element>
            <element name="Floor" type="string"></element>
            <element name="Floors" type="string"></element>
            <element name="Square" type="string"></element>
            <element name="Price" type="string"></element>
        </all>
    </complexType>


</schema>

=== denone2000/JD2018-08-21/src/by/it/voinilo/jd02/jd02_09/Persons+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation = "http://beans.jd02_09.jd02.voinilo.it.by/xml/Persons Persons.xsd"
    xmlns = "http://beans.jd02_09.jd02.voinilo.it.by/xml/Persons">
    <Person>
        <Email>asd@mail.ru</Email>
        <Nickname>asd</Nickname>
        <Password>1234</Password>
        <Ads>
            <Ad>
                <Rooms>2</Rooms>
                <Description>Квартира в центре города</Description>
                <Addres>Пр.Пушкина 2-3-4</Addres>
                <Floor>2</Floor>
                <Floors>5</Floors>
                <Square>21</Square>
                <Price>300k</Price>
            </Ad>
            <Ad >
                <Rooms>3</Rooms>
                <Description>Квартира в спальном районе</Description>
                <Addres>Центральная, 212</Addres>
                <Floor>4</Floor>
                <Floors>10</Floors>
                <Square>43</Square>
                <Price>250k</Price>
            </Ad>
            <Ad >
                <Rooms>1</Rooms>
                <Description>Квартира рядом с метро</Description>
                <Addres>Победителей,24</Addres>
                <Floor>1</Floor>
                <Floors>10</Floors>
                <Square>25</Square>
                <Price>221k</Price>
            </Ad>
        </Ads>
    </Person>

</Persons>
