=== denone2000/JD2018-08-21/src/by/it/korzik/jd02/jd02_07/v1/Persons_XSD.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.by.it.korzik/"
        xmlns:tns="http://www.by.it.korzik/"
        elementFormDefault="qualified">
    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person"
                         type="tns:Person"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Name" type="string"/>
            <element name="NickName" type="string"/>
            <element name="Email" type="string"/>
            <element name="Password" type="string"/>
            <element name="Number" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="Ad"
                     type="tns:Ad"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <sequence>
        <element name="Model" type="string"/>
            <element name="CarType" type="string"/>
            <element name="FuelType" type="string"/>
            <element name="FuelPer100KM" type="float"/>
            <element name="Doors" type="positiveInteger"/>
            <element name="Price" type="positiveInteger"/>
        </sequence>
        <attribute name="year" type="positiveInteger" use="required"/>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/korzik/jd02/jd02_07/v1/Persons+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns:xmln="http://www.w3.org/2001/XMLSchema-instance"
         xmlns= "http://www.by.it.korzik/"
         xmln:schemaLocation="http://www.by.it.korzik/ Persons_XSD.xsd">
    <Person>
        <Name>Peter</Name>
        <NickName>Peter</NickName>
        <Email>peter@gmail.com</Email>
        <Password>iampeter</Password>
        <Number>+3751929394</Number>
        <Ads>
            <Ad year="1996">
                <Model>someCar</Model>
                <CarType>sedan</CarType>
                <FuelType>diesel</FuelType>
                <FuelPer100KM>10.3</FuelPer100KM>
                <Doors>5</Doors>
                <Price>2400</Price>
            </Ad>
            <Ad year="1999">
                <Model>someCar</Model>
                <CarType>sedan</CarType>
                <FuelType>92</FuelType>
                <FuelPer100KM>8.3</FuelPer100KM>
                <Doors>5</Doors>
                <Price>3600</Price>
            </Ad>
            <Ad year="1982">
                <Model>someCar</Model>
                <CarType>sedan</CarType>
                <FuelType>92</FuelType>
                <FuelPer100KM>11.8</FuelPer100KM>
                <Doors>5</Doors>
                <Price>1000</Price>
            </Ad>
        </Ads>
    </Person>
    <Person>
        <Name>asda</Name>
        <NickName>sda</NickName>
        <Email>paaaasdwwwes@gmail.com</Email>
        <Password>qweasdzxcasdewq123</Password>
        <Number>+78898889554</Number>
        <Ads>
            <Ad year="2012">
                <Model>someCar</Model>
                <CarType>sedan</CarType>
                <FuelType>98</FuelType>
                <FuelPer100KM>6.9</FuelPer100KM>
                <Doors>3</Doors>
                <Price>24000</Price>
            </Ad>
            <Ad year="1996">
                <Model>someCar</Model>
                <CarType>sedan</CarType>
                <FuelType>diesel</FuelType>
                <FuelPer100KM>10.3</FuelPer100KM>
                <Doors>5</Doors>
                <Price>2400</Price>
            </Ad>
            <Ad year="1996">
                <Model>someCar</Model>
                <CarType>sedan</CarType>
                <FuelType>diesel</FuelType>
                <FuelPer100KM>10.3</FuelPer100KM>
                <Doors>5</Doors>
                <Price>2400</Price>
            </Ad>
        </Ads>
    </Person>
</Persons>
