=== denone2000/JD2018-08-21/src/by/it/bindyuk/jd02_09/Transport.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.bindyuk.it.by/"
        xmlns:tns="http://beans.jd02_09.bindyuk.it.by/"
        elementFormDefault="qualified">
    <element name="transport">
        <complexType>
            <sequence>
                <element name="transportType"
                         type="tns:transportType"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="transportType">
            <sequence>
                <element name="from" type="tns:from"/>
                <element name="pointTo" type="tns:pointTo"/>
                <element name="date" type="tns:date"/>
                <element name="typeTicket" type="string"/>
                <element name="price" type="string"/>
            </sequence>
            <attribute name="type"
            type="string" use="required">
            </attribute>
        </complexType>


    <complexType name="from">

            <sequence>
                <element name="cityOf" type="string"/>
                <element name="railwayStOf" type="string"/>
            </sequence>

    </complexType>

    <complexType name="pointTo">

            <sequence>
                <element name="cityTo" type="string"/>
                <element name="railwayStTo" type="string"/>
            </sequence>

    </complexType>

    <complexType name="date">

            <sequence>
                <element name="day" type="positiveInteger"/>
                <element name="month" type="string"/>
                <element name="year" type="positiveInteger"/>
            </sequence>

    </complexType>

    <element name="typeTicket" type="string"/>
    <element name="price" type="positiveInteger"/>

</schema>

=== denone2000/JD2018-08-21/src/by/it/bindyuk/jd02_07/Transport+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<transport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://bindyuk.by/"
           xsi:schemaLocation="http://bindyuk.by/ Transport.xsd"
>
    <transportType type="поезд">
        <from>
            <cityOf>Минск</cityOf>
            <railwayStOf>Минск-Пассажирский</railwayStOf>
        </from>
        <pointTo>
            <cityTo>Гродно</cityTo>
            <railwayStTo>Гродно-ЖД</railwayStTo>
        </pointTo>
        <date>
            <day>20</day>
            <month>Ноябрь</month>
            <year>2018</year>
        </date>
        <typeTicket>Взрослый</typeTicket>
        <price>4.20</price>
    </transportType>

    <transportType type="поезд">
        <from>
            <cityOf>Витебск</cityOf>
            <railwayStOf>Витебск-Пассажирский</railwayStOf>
        </from>
        <pointTo>
            <cityTo>Минск</cityTo>
            <railwayStTo>Минск-ПСЖ</railwayStTo>
        </pointTo>
        <date>
            <day>13</day>
            <month>Декабрь</month>
            <year>2018</year>
        </date>
        <typeTicket>Взрослый</typeTicket>
        <price>9.5</price>
    </transportType>
</transport>
