=== denone2000/JD2018-08-21/src/by/it/litvin/jd02_07/Dota.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://litvin.it.by/"
        xmlns:tns="http://litvin.it.by/"
        elementFormDefault="qualified">
    <element name="Dota">
        <complexType>
            <sequence>
                <element name="Team"
                         type="tns:Team"
                         minOccurs="1"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Team">
        <sequence>
            <element name="Region" type="string"/>
            <element name="Name" type="string"/>
            <element name="Birth" type="positiveInteger"/>
            <element name="PlayerRoster" type="tns:PlayerRoster"/>
        </sequence>
    </complexType>

    <complexType name="PlayerRoster">
        <sequence>
            <element
                    name="Temporary"
                    type="tns:Temporary"
                    minOccurs="1"
                    maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Temporary">
        <sequence>
            <element name="Support" type="string"/>
            <element name="SemiSupport" type="string"/>
            <element name="HardLane" type="string"/>
            <element name="Mid" type="string"/>
            <element name="EasyLane" type="string"/>
        </sequence>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/litvin/jd02_07/Dota+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Dota xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://litvin.it.by/"
         xsi:schemaLocation="http://litvin.it.by/ Dota.xsd"
>

        <Team>
            <Region>EU</Region>
            <Name>OG</Name>
            <Birth>2015</Birth>
            <PlayerRoster>
                <Temporary>
                    <Support>NOtail</Support>
                    <SemiSupport>JerAx</SemiSupport>
                    <HardLane>Seb</HardLane>
                    <Mid>Topson</Mid>
                    <EasyLane>ana</EasyLane>
                </Temporary>
            </PlayerRoster>
        </Team>
        <Team>
            <Region>RU</Region>
            <Name>VirtusPro</Name>
            <Birth>2012</Birth>
            <PlayerRoster>
                <Temporary>
                    <Support>Solo</Support>
                    <SemiSupport>Rodjer</SemiSupport>
                    <HardLane>pasha</HardLane>
                    <Mid>Noone</Mid>
                    <EasyLane>RAMZES</EasyLane>
                </Temporary>
            </PlayerRoster>
        </Team>
    </Dota>
