<?xml version="1.0" encoding="UTF-8"   standalone="yes" ?>
<!DOCTYPE Dota [
        <!ELEMENT Dota (Team)+>
        <!ELEMENT Team (Region, Name, Birth, PlayerRoster)>
        <!ELEMENT Region (#PCDATA)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Birth (#PCDATA)>
        <!ELEMENT PlayerRoster (Temporary)+>
        <!ELEMENT Temporary (Support, SemiSupport, HardLane, Mid, EasyLane)>
        <!ELEMENT Support (#PCDATA)>
        <!ELEMENT SemiSupport (#PCDATA)>
        <!ELEMENT HardLane (#PCDATA)>
        <!ELEMENT Mid (#PCDATA)>
        <!ELEMENT EasyLane (#PCDATA)>
        ]>
<Dota>
    <Team>
        <Region>EU</Region>
        <Name>OG</Name>
        <Birth>2015</Birth>
        <PlayerRoster>
            <Temporary>
                <Support>NOtail</Support>
                <SemiSupport>JerAx</SemiSupport>
                <HardLane>Seb</HardLane>
                <Mid>Topson</Mid>
                <EasyLane>ana</EasyLane>
            </Temporary>
        </PlayerRoster>
    </Team>
    <Team>
        <Region>RU</Region>
        <Name>VirtusPro</Name>
        <Birth>2012</Birth>
        <PlayerRoster>
            <Temporary>
                <Support>Solo</Support>
                <SemiSupport>Rodjer</SemiSupport>
                <HardLane>pasha</HardLane>
                <Mid>Noone</Mid>
                <EasyLane>RAMZES</EasyLane>
            </Temporary>
        </PlayerRoster>
    </Team>
</Dota>