=== denone2000/JD2018-08-21/src/by/it/nesterovich/jd02_07/Films.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://nesterovich.it.by/"
        xmlns:tns="http://nesterovich.it.by/"
        elementFormDefault="qualified">
    <element name="Films">
        <complexType>
            <sequence>
                <element name="Film"
                         type="tns:Film"
                         minOccurs="0"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Film">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Genre" type="string"/>
            <element name="Country" type="string"/>
            <element name="YearOfIssue" type="positiveInteger"/>
            <element name="Duration" type="positiveInteger"/>
            <element name="Cinemas" type="tns:Cinemas"/>
        </sequence>
    </complexType>
    <complexType name="Cinemas">
        <sequence>
            <element name="Cinema"
                     type="tns:Cinema"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Cinema">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Address" type="string"/>
        </sequence>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/nesterovich/jd02_07/Films+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Films xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns = "http://nesterovich.it.by/"
       xsi:schemaLocation="http://nesterovich.it.by/ Films.xsd"
>
    <Film>
        <Name>Расплата</Name>
        <Genre>боевик, триллер, драмма</Genre>
        <Country>США</Country>
        <YearOfIssue>2016</YearOfIssue>
        <Duration>128</Duration>
        <Cinemas>
            <Cinema>
                <Name>Беларусь</Name>
                <Address>ул. Романовская Слобода 28</Address>
            </Cinema>
            <Cinema>
                <Name>Октябрь</Name>
                <Address>пр. Независимости 73</Address>
            </Cinema>
        </Cinemas>
    </Film>
    <Film>
        <Name>Робот по имени Чаппи</Name>
        <Genre>фантастика, боевик, триллер, драма, криминал</Genre>
        <Country>США, ЮАР</Country>
        <YearOfIssue>2015</YearOfIssue>
        <Duration>120</Duration>
        <Cinemas>
            <Cinema>
                <Name>Аврора</Name>
                <Address>ул. Притыцкого 23</Address>
            </Cinema>
        </Cinemas>
    </Film>
</Films>
