=== denone2000/JD2018-08-21/src/by/it/nesterovich/jd02_07/Films.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Films (Film)+>
        <!ELEMENT Film (Name, Genre, Country, YearOfIssue, Duration, Cinemas )>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Genre (#PCDATA)>
        <!ELEMENT Country (#PCDATA)>
        <!ELEMENT YearOfIssue (#PCDATA)>
        <!ELEMENT Duration (#PCDATA)>
        <!ELEMENT Cinemas (Cinema)+>
        <!ELEMENT Cinema (NameCinema, Address)>
        <!ELEMENT NameCinema (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>

=== denone2000/JD2018-08-21/src/by/it/nesterovich/jd02_07/Films+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Films SYSTEM "Films.dtd">
<Films>
    <Film>
        <Name>Расплата</Name>
        <Genre>боевик, триллер, драмма</Genre>
        <Country>США</Country>
        <YearOfIssue>2016</YearOfIssue>
        <Duration>128</Duration>
        <Cinemas>
            <Cinema>
                <NameCinema>Беларусь</NameCinema>
                <Address>ул. Романовская Слобода 28</Address>
            </Cinema>
            <Cinema>
                <NameCinema>Октябрь</NameCinema>
                <Address>пр. Независимости 73</Address>
            </Cinema>
        </Cinemas>
    </Film>
    <Film>
        <Name>Робот по имени Чаппи</Name>
        <Genre>фантастика, боевик, триллер, драма, криминал</Genre>
        <Country>США, ЮАР</Country>
        <YearOfIssue>2015</YearOfIssue>
        <Duration>120</Duration>
        <Cinemas>
            <Cinema>
                <NameCinema>Аврора</NameCinema>
                <Address>ул. Притыцкого 23</Address>
            </Cinema>
        </Cinemas>
    </Film>
</Films>
