=== denone2000/JD2018-08-21/src/by/it/artemliashkov/jd02_09/Companies.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.artemliashkov.it.by/"
        xmlns:tns="http://beans.jd02_09.artemliashkov.it.by/"
        elementFormDefault="qualified">
    <element name="Companies">
        <complexType>
            <sequence>
                <element name="Company"
                         type="tns:Company"
                         minOccurs="0"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Company">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Role" type="string"/>
            <element name="Country" type="string"/>
            <element name="AmountAgents" type="positiveInteger"/>
            <element name="Agents" type="tns:Agents"/>
        </sequence>
    </complexType>
    <complexType name="Agents">
        <sequence>
            <element name="Agent"
                     type="tns:Agent"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Agent">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Address" type="string"/>
        </sequence>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/artemliashkov/jd02_07/Companies+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Companies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns = "http://artemliashkov.it.by/"
       xsi:schemaLocation="http://artemliashkov.it.by/ Companies.xsd">

        <Company>
            <Name>Компания ТАСК</Name>
            <Role>Страховая</Role>
            <Country>Беларусь</Country>
            <AmountAgents>3278</AmountAgents>
            <Agents>
                <Agent>
                    <Name>Вера Николаевна</Name>
                    <Address>ул. Острошицкая 11</Address>
                </Agent>
                <Agent>
                    <Name>Анна Сергеевна</Name>
                    <Address>пр. Независимости 73</Address>
                </Agent>
            </Agents>
        </Company>
        <Company>
            <Name>Компания Белнефтестрах</Name>
            <Role>Страховая</Role>
            <Country>Беларусь</Country>
            <AmountAgents>612</AmountAgents>
            <Agents>
                <Agent>
                    <Name>Галина Александрова</Name>
                    <Address>ул. Городецкая 36</Address>
                </Agent>
                <Agent>
                    <Name>Инна Тарасовна</Name>
                    <Address>ул. Академика Купревича 27</Address>
                </Agent>
            </Agents>
        </Company>
    </Companies>
