=== denone2000/JD2018-08-21/src/by/it/yaroshchuk/jd02_07/resumes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://yaroshchuk.it.by/"
        xmlns:tns="http://yaroshchuk.it.by/"
        elementFormDefault="qualified">
    <element name="resumes">
        <complexType>
            <sequence>
                <element name="resume"
                         type="tns:resume"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="resume">
        <sequence>
            <element name="fullName" type="string" />
            <element name="dob" type="date"/>
            <element name="address" type="tns:address"/>
            <element name="phone" type="string" maxOccurs="unbounded"/>
            <element name="education" type="tns:education" maxOccurs="unbounded"/>
            <element name="experience" type="tns:experience" maxOccurs="unbounded"/>
            <element name="comments" type="string"/>
        </sequence>
        <attribute name="login" type="tns:Login" use="required"/>
    </complexType>
    <simpleType name="Login">
        <restriction base="ID"/>
    </simpleType>

    <complexType name="address">
        <sequence>
            <element name="country" type="string"/>
            <element name="city" type="string"/>
            <element name="street" type="string"/>
        </sequence>
    </complexType>

    <complexType name="education">
        <sequence>
            <element name="institution" type="string"/>
            <element name="degree">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="degree1"/>
                        <enumeration value="degree2"/>
                        <enumeration value="degree3"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="startYear" type="gYear"/>
            <element name="graduateYear" type="gYear"/>
        </sequence>
    </complexType>

    <complexType name="experience">
        <sequence>
            <element name="workplace" type="string"/>
            <element name="post" type="string"/>
            <element name="workPeriodStart" type="gYearMonth"/>
            <element name="workPeriodEnd" type="gYearMonth"/>
        </sequence>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/yaroshchuk/jd02_09/resumes+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<resumes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://bean.jd02_09.yaroshchuk.it.by/"
        xsi:schemaLocation="http://bean.jd02_09.yaroshchuk.it.by/ resumes.xsd">
    <resume login="login1">
        <fullName>Full Name</fullName>
        <dob>1990-05-12</dob>

        <address>
            <country>Country</country>
            <city>City</city>
            <street>Street 51</street>
        </address>

        <phone>45845654</phone>

        <education>
            <institution>Institution name</institution>
            <degree>degree1</degree>
            <startYear>2010</startYear>
            <graduateYear>2015</graduateYear>
        </education>

        <experience>
            <workplace>Workplace</workplace>
            <post>Post</post>
            <workPeriodStart>2008-10</workPeriodStart>
            <workPeriodEnd>2010-10</workPeriodEnd>
        </experience>

        <comments>Some comments</comments>
    </resume>

    <resume login="login2">
        <fullName>Full Name2</fullName>
        <dob>1992-05-12</dob>

        <address>
            <country>Country2</country>
            <city>City2</city>
            <street>Street 52</street>
        </address>

        <phone>2222222222</phone>

        <education>
            <institution>Institution name2</institution>
            <degree>degree2</degree>
            <startYear>2012</startYear>
            <graduateYear>2017</graduateYear>
        </education>

        <experience>
            <workplace>Workplace2</workplace>
            <post>Post2</post>
            <workPeriodStart>2008-10</workPeriodStart>
            <workPeriodEnd>2010-10</workPeriodEnd>
        </experience>

        <comments>Some comments2</comments>
    </resume>
</resumes>
