=== denone2000/JD2018-08-21/src/by/it/yaroshchuk/jd02_07/resumes.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT resumes (resume)+>
        <!ELEMENT resume (fullName, dob, address, phone, email, education, experience, comments)>
        <!ATTLIST resume
                login ID #REQUIRED>
        <!ELEMENT fullName (#PCDATA)>
        <!ELEMENT dob (#PCDATA)>
        <!ELEMENT address (country, city, street)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT phone (#PCDATA)+>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT education (institution, degree, startYear, graduateYear)+>
        <!ELEMENT institution (#PCDATA)>
        <!ELEMENT degree (#PCDATA)>
        <!ELEMENT startYear (#PCDATA)>
        <!ELEMENT graduateYear (#PCDATA)>
        <!ELEMENT experience (workplace, post, workPeriodStart, workPeriodEnd)*>
        <!ELEMENT workplace (#PCDATA)>
        <!ELEMENT post (#PCDATA)>
        <!ELEMENT workPeriodStart (#PCDATA)>
        <!ELEMENT comments (#PCDATA)>
        <!ELEMENT workPeriodEnd (#PCDATA)>

=== denone2000/JD2018-08-21/src/by/it/yaroshchuk/jd02_07/resumes+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE resumes SYSTEM "resumes.dtd">
<resumes>
    <resume login="LOGIN1">
        <fullName>Фамилия Имя Отчество</fullName>
        <dob>15.06.1995</dob>
        <address>
            <country>Страна</country>
            <city>Город</city>
            <street>Улица</street>
        </address>
        <phone>568547895</phone>
        <email>email@email.com</email>
        <education>
            <institution>Название учереждения</institution>
            <degree>degree1</degree>
            <startYear>2010</startYear>
            <graduateYear>2015</graduateYear>
        </education>
        <experience>
            <workplace>Место работы</workplace>
            <post>Должность</post>
            <workPeriodStart>2008-10</workPeriodStart>
            <workPeriodEnd>2010-10</workPeriodEnd>
        </experience>
        <comments>Комментарии</comments>
    </resume>
</resumes>
