=== denone2000/JD2018-08-21/src/by/it/yarmolenka/jd02_07/05.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://yarmolenka.it-academy.by/xml/Customers"
        xmlns:tns="http://yarmolenka.it-academy.by/xml/Customers"
        elementFormDefault="qualified">
    <element name="Customers">
        <complexType>
            <sequence>
                <element name="Player"
                         type="tns:player"
                         minOccurs="2"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="player">
    <sequence>
        <element name="Name" type="string"/>
        <element name="BirthDate" type="tns:birthdate"/>
        <element name="Phone" type="positiveInteger"/>
        <element name="Address" type="tns:address"/>
        <element name="Status" type="string"/>
        <element name="Bar" type="string"/>
        <element name="Cashback" type="float"/>
    </sequence>
    </complexType>
    <complexType name="address">
        <sequence>
            <element name="Country" type="string"/>
            <element name="City" type="string"/>
            <element name="Street" type="string"/>
        </sequence>
    </complexType>
    <complexType name="birthdate">
        <sequence>
            <element name="Year" type="string"/>
            <element name="Month" type="string"/>
            <element name="Day" type="string"/>
        </sequence>
    </complexType>
</schema>

=== denone2000/JD2018-08-21/src/by/it/yarmolenka/jd02_07/06 +XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Customers xmlns="http://yarmolenka.it-academy.by/xml/Customers"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://yarmolenka.it-academy.by/xml/Customers 05.xsd">

    <Player>
        <Name>Alla Pugacheva</Name>
        <BirthDate>
            <Year>1939</Year>
            <Month>04</Month>
            <Day>15</Day>
        </BirthDate>
        <Phone>3822773</Phone>
        <Address>
            <Country>Russia</Country>
            <City>Moscow</City>
            <Street>Nikolskaya 27</Street>

        </Address>
        <Status>Platinum</Status>
        <Bar>Unlimited</Bar>
        <Cashback>0.2</Cashback>
    </Player>
    <Player>
        <Name>Maksim Galkin</Name>
        <BirthDate>
            <Year>1976</Year>
            <Month>06</Month>
            <Day>18</Day>
        </BirthDate>
        <Phone>3884773</Phone>
        <Address>
            <Country>Russia</Country>
            <City>Moscow</City>
            <Street>Dmitrovskaya 48</Street>
        </Address>
        <Status>Gold</Status>
        <Bar>Unlimited</Bar>
        <Cashback>0.1</Cashback>
    </Player>
</Customers>

=== denone2000/JD2018-08-21/src/by/it/yarmolenka/jd02_07/06+ns+XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:ns="http://yarmolenka.it-academy.by/xml/Customers"
          xsi:schemaLocation="http://yarmolenka.it-academy.by/xml/Customers 05.xsd">
    <ns:Player>
        <ns:Name>Alla Pugacheva</ns:Name>
        <ns:BirthDate>
            <ns:Year>1939</ns:Year>
            <ns:Month>04</ns:Month>
            <ns:Day>15</ns:Day>
        </ns:BirthDate>
        <ns:Phone>3822773</ns:Phone>
        <ns:Address>
            <ns:Country>Russia</ns:Country>
            <ns:City>Moscow</ns:City>
            <ns:Street>Nokolskaya 27</ns:Street>
        </ns:Address>
        <ns:Status>Platinum</ns:Status>
        <ns:Bar>Unlimited</ns:Bar>
        <ns:Cashback>0.2</ns:Cashback>
    </ns:Player>
    <ns:Player>
        <ns:Name>Maksim Galkin</ns:Name>
        <ns:BirthDate>
            <ns:Year>1976</ns:Year>
            <ns:Month>06</ns:Month>
            <ns:Day>18</ns:Day>
        </ns:BirthDate>
        <ns:Phone>3822773</ns:Phone>
        <ns:Address>
            <ns:Country>Russia</ns:Country>
            <ns:City>Moscow</ns:City>
            <ns:Street>Dmitrovskaya 48</ns:Street>
        </ns:Address>
        <ns:Status>Gold</ns:Status>
        <ns:Bar>Unlimited</ns:Bar>
        <ns:Cashback>0.1</ns:Cashback>
    </ns:Player>
</ns:Customers>
